version: "3.1"

networks:
  web:
    external:
      name: web

services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - web
    environment:
      # - URL=http://18.197.148.92/
      - URL=http://localhost:3001
      - STRAPI_DISABLE_UPDATE_NOTIFICATION=true
      - STRAPI_TELEMETRY_DISABLED=true
      - NODE_ENV=production
      - BROWSER=false
      - HOST=0.0.0.0
      - PORT=3000
      - APP_KEYS="toBeModified1,toBeModified2"
      - API_TOKEN_SALT=tobemodified
      - ADMIN_JWT_SECRET=tobemodified
      - JWT_SECRET=tobemodified
      - DATABASE_FILENAME=/data/db.sqlite
      - AWS_ACCESS_KEY_ID="module.backend-apprunner.access_key_id"
      - AWS_ACCESS_SECRET="module.backend-apprunner.access_key_secret"
      - AWS_REGION=eu-central-1
      - AWS_BUCKET_NAME=tradeshow
    ports:
      - "3001:3000"
    volumes:
      - ./strapi-data:/data

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - strapi
    ports:
      - "3000:3000"
    networks:
      - web
    environment:
      - STRAPI_ENDPOINT_URL=http://strapi:3000
      - NEXT_PUBLIC_STRAPI_ENDPOINT_URL=http://localhost:3001
      - STRAPI_API_KEY=bdd57bfdeada6d4d2811d57ab3e925a3bd41ac1fa3151616d3ba16c7082090886dc6cc7cf680a195fe1b22470d2321f8d0917a66b72eb3e50e15fe13a07e6f0b121d5870e815afea1a1fa773f5793fa7e5cd5eadf69b9fb16d72e557047c824483e262234f005957e52a82a6427c8820e1a9d30c5961055a55c474857fb20599