version: "3.1"

networks:
  default:
    external:
      name: traefik_default

services:
  traefik:
    image: traefik:latest
    restart: always
    volumes:
      - ./data:/etc/traefik:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--serversTransport.insecureSkipVerify=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--providers.docker.network=traefik_default"
      - "--providers.file.filename=dynamic.toml"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--certificatesresolvers.http.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.http.acme.email=miro.rauhala@tuni.fi"
      - "--certificatesresolvers.http.acme.httpchallenge.entrypoint=http"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.gemeinsam-stark.tk`)"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.middlewares=auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      # - "traefik.http.routers.traefik-secure.tls.domains[0].main=gemeinsam-stark.tk"

  strapi:
    image:  ghcr.io/mirorauhala/trade-back:latest
    restart: unless-stopped
    networks:
      - default
    environment:
      - URL=${URL}
      - STRAPI_DISABLE_UPDATE_NOTIFICATION=true
      - STRAPI_TELEMETRY_DISABLED=true
      - NODE_ENV=production
      - BROWSER=false
      - HOST=0.0.0.0
      - PORT=3000
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_FILENAME=${DATABASE_FILENAME}
    volumes:
      - ./strapi-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`strapi.gemeinsam-stark.tk`)"
      - "traefik.http.services.strapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.strapi.entrypoints=https"
      - "traefik.http.routers.strapi.tls=true"
      - "traefik.http.routers.strapi.tls.certresolver=http"

  next:
    image: ghcr.io/mirorauhala/trade-front:latest
    restart: unless-stopped
    depends_on:
      - strapi
    networks:
      - default
    environment:
      - STRAPI_ENDPOINT_URL=${STRAPI_ENDPOINT_URL}
      - NEXT_PUBLIC_STRAPI_ENDPOINT_URL=${NEXT_PUBLIC_STRAPI_ENDPOINT_URL}
      - STRAPI_API_KEY=${STRAPI_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gemeinsam-stark.tk`, `www.gemeinsam-stark.tk`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=http"
