version: "3.1"

volumes:
  db_data:
    driver: local

services:

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data